### ISSUE TITLE
Sponsors and Sponsors page

### ISSUE THREAD

**Issue by michael-beaver** [dnhess/siggame.github.io#5]
We need the sponsors page to be fleshed out. This can potentially be very similar to the one at siggame.io/blog

I would also like to see the sponsors' images on the front page, maybe have the pictures of all of them, each linking to its section on the sponsors page, and an overall "See more about our sponsors" link that points you to the sponsors page.

**Comment by dnhess** [comment]
I copied over the sponsors page from siggame.io/blog. The images are fairly big and the text takes up the entire screen. It doesn't look too bad, and it kind of fits the landing page theme. We still need the images on the landing page.

**Comment by dnhess** [comment]
Finished this issue with commits [fe388e8d](https://github.com/dnhess/siggame.github.io/commit/fe388e8d71476432cce57348eb311d0ea1f4ae96) and [7a92eb7](https://github.com/dnhess/siggame.github.io/commit/7a92eb71fc4427601641bd7f571daf960b25f0eb)
