### ISSUE TITLE
Merging in the blog

### ISSUE THREAD

**Issue by michael-beaver** [dnhess/siggame.github.io#7]
The blog posts need to be merged in to the landing page site as link at the top. Essentially this will mean that the front page of the current blog will just be a link on the new site, but with the new site's templating.

This will likely be a bit more work than some of the other importing.

**Comment by renodubois** [comment]
Put into place with [this](https://github.com/dnhess/siggame.github.io/commit/09142b8800e562077cfcd0db7b3205c81c2b1e4f) commit.
